name: Automated Tests

on: pull_request

jobs:
  vitest:
    name: Vitest Ubuntu

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/iron"]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm ci

      - name: Run tests
        run: pnpm test
